url: "https://SungJaeShin.github.io/"
baseurl: ""

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

paginate: 10
paginate_path: "/blog/page:num/"

title: SungJae Shin
subtitle: For My best future  

#left_side:
#  background_image: "./assets/images/left-background.jpg"
#  background_color: "#F00"
#  close_button_color: "#F00"
#  text_color: "#F00"

footer:
  copyright_text: "&copy; Christian Ezeani"

# Side Menu Links
menu:
  - text: Home
    link: /
    icon: ""

  - text: SLAM
    link: /
    icon: ""

  - text: Deep Learning 
    link: /
    icon: ""

  - text: Paper Survey
    link: /
    icon: ""

  - text: About Me
    link: /posts
    icon: ""

# Socialmedia Icons
social_icons:
  - name: github
    link: https://github.com/SungJaeShin
    icon: fab fa-github-square


    
